### ISSUE TITLE
JRE 11 not working for the java server for WSL. Proposing changing to Java 17 to fix

### ISSUE THREAD

**Issue by Magdk01** [MAvis-DTU/02182-MAvis-Code-Handout#1]
I am not sure this is a just a local linux problem, but trying to run the java commands from a WSL ubuntu 22.04.3 LTS setup with JRE 11 as stated in the [readme line](https://github.com/MAvis-DTU/02182-MAvis-Code-Handout/blob/3813cc74cc00d2f375d8f96f6dec6897318b8e79/searchclient/README.md?plain=1#L7C1-L7C82) returns a versioning problem:
`Error: LinkageError occurred while loading main class dk.dtu.compute.mavis.server.Server
        java.lang.UnsupportedClassVersionError: dk/dtu/compute/mavis/server/Server has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

In this [stackoverflow](https://stackoverflow.com/questions/47457105/class-has-been-compiled-by-a-more-recent-version-of-the-java-environment) it seems that the classfile version 61.0 needs at least java 17 to run.

I was able to get the client running by installing JRE 17 using:
`sudo apt install openjdk-17-jdk -y
`

**Comment by thomas-bolander** [comment]
Yes, sorry, I built a new server with java 17, I updated the readme.

  T

On 14 Feb 2024, at 12.58, Magnus Vinjebo ***@***.***> wrote:



I am not sure this is a just a local linux problem, but trying to run the java commands from a WSL ubuntu 22.04.3 LTS setup with JRE 11 as stated in the readme line<https://github.com/MAvis-DTU/02182-MAvis-Code-Handout/blob/3813cc74cc00d2f375d8f96f6dec6897318b8e79/searchclient/README.md?plain=1#L7C1-L7C82> returns a versioning problem:
Error: LinkageError occurred while loading main class dk.dtu.compute.mavis.server.Server java.lang.UnsupportedClassVersionError: dk/dtu/compute/mavis/server/Server has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

In this stackoverflow<https://stackoverflow.com/questions/47457105/class-has-been-compiled-by-a-more-recent-version-of-the-java-environment> it seems that the classfile version 61.0 needs at least java 17 to run.

I was able to get the client running by installing JRE 17 using:
sudo apt install openjdk-17-jdk -y
